/* tslint:disable */
/* eslint-disable */
/**
 * Mocode CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to fork a session.
 * @export
 * @interface ForkSessionRequest
 */
export interface ForkSessionRequest {
    /**
     * The turn index to fork at (0-based, user messages). Messages up to this turn will be copied.
     * @type {number}
     * @memberof ForkSessionRequest
     */
    turnIndex?: number | null;
}

/**
 * Check if a given object implements the ForkSessionRequest interface.
 */
export function instanceOfForkSessionRequest(value: object): value is ForkSessionRequest {
    return true;
}

export function ForkSessionRequestFromJSON(json: any): ForkSessionRequest {
    return ForkSessionRequestFromJSONTyped(json, false);
}

export function ForkSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForkSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'turnIndex': json['turn_index'] == null ? undefined : json['turn_index'],
    };
}

export function ForkSessionRequestToJSON(json: any): ForkSessionRequest {
    return ForkSessionRequestToJSONTyped(json, false);
}

export function ForkSessionRequestToJSONTyped(value?: ForkSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'turn_index': value['turnIndex'],
    };
}
